// 200 creative & behavioural nudges — cycled randomly on iOS/iPadOS
export const nudges = [
  // — change of scene / body —
  "Open the nearest window and look outside for one full minute without any agenda.",
  "Step outside and walk around the block — let your mind wander completely.",
  "Move to a different room and sit somewhere you don't usually sit.",
  "Stand up, shake out your hands, and take three slow deep breaths.",
  "Find a patch of sunlight and stand in it for a moment.",
  "Make a cup of tea or coffee and drink it away from any screen.",
  "Go outside and look at the sky — notice the colour, the clouds, the light.",
  "Walk to the furthest point you can reach in 5 minutes, then walk back.",
  "Take your shoes off and feel the ground beneath your feet.",
  "Look out a window and find three things you've never really noticed before.",
  "Step outside, close your eyes, and just listen to the sounds around you.",
  "Walk somewhere new — even just a different street — and notice what's there.",
  "Sit in a different chair than you normally would and see how the room looks.",
  "Take a slow walk without your phone. Just walk.",
  "Find the highest point nearby and look out from it.",
  "Splash cold water on your face and notice how you feel afterward.",
  "Walk somewhere that has trees, grass, or water — even briefly.",
  "Do one minute of gentle stretching — neck, shoulders, arms.",
  "Go find a view you haven't looked at today.",
  "Walk outside and notice the first interesting thing you see.",

  // — shift your perspective —
  "Imagine your problem as if it belonged to a stranger — what would you tell them?",
  "Shrink it: what's the smallest possible version of this that still matters?",
  "Imagine explaining this to a curious ten-year-old.",
  "What would the most optimistic person you know say about this?",
  "Write down the opposite of your current approach and see what it suggests.",
  "Pretend you're seeing this for the first time, as a complete beginner.",
  "What would this look like if it were surprisingly simple?",
  "Think about the person who will benefit most — what do they actually need?",
  "Imagine looking back at this moment from five years in the future.",
  "What's the hidden gift in this difficulty?",
  "Ask: what would I do if I weren't afraid of getting it wrong?",
  "Consider the problem from someone else's cultural or professional perspective.",
  "Flip the constraint — what if the limitation is actually an advantage?",
  "What's the kindest interpretation of the situation?",
  "If you had to solve this with half the resources, what would change?",
  "What would a child find delightful about this challenge?",
  "Pretend you already know the answer — what does it feel like?",
  "What would the wisest person you've ever met notice here?",
  "Consider: what question haven't I asked yet that might unlock this?",
  "Look at the situation as if it's already resolved — what had to happen?",

  // — small creative acts —
  "Sketch three rough shapes on paper — they don't need to mean anything.",
  "Write one sentence about how you're feeling right now, then tear it up.",
  "Doodle freely for two minutes — no goal, just marks on a page.",
  "Hum a melody to yourself, even a made-up one.",
  "Rearrange three objects on your desk into something that feels intentional.",
  "Take a photo of something ordinary that suddenly seems interesting.",
  "Write down five words that capture the feeling you're chasing.",
  "Draw a very rough map of somewhere you know well.",
  "Make a short list of things that made you smile this week.",
  "Write the first sentence of a story that begins right where you are now.",
  "Name your current mood as if it were a weather system.",
  "Pick an object near you and describe it in three unexpected ways.",
  "Write a two-line poem — it doesn't have to be good.",
  "List five materials, textures, or colours you find beautiful.",
  "Invent a word for something that doesn't have one yet.",
  "Sketch the view from where you're sitting in under two minutes.",
  "Write down the strangest thing you can remember happening to you.",
  "Find something in your environment that represents a feeling you have.",
  "Make a tiny collage in your mind — three unrelated images that somehow belong together.",
  "Describe the best meal you ever ate as if you were writing a postcard.",

  // — thinking & reflection —
  "Write for three minutes without stopping — anything at all.",
  "List ten things you're curious about right now, big or small.",
  "What's one thing you're genuinely proud of that you haven't celebrated enough?",
  "What's a belief you hold that most people around you don't share?",
  "Write down the three things you'd focus on if you only had one more week on this project.",
  "What would you do differently if no one was watching or judging?",
  "Name one thing that's been draining your energy — can you set it aside for now?",
  "What's one small thing you could do today that would make tomorrow easier?",
  "Write down a question you've been avoiding.",
  "What's something you've been meaning to say to someone?",
  "If your work had a soundtrack right now, what would it sound like?",
  "List three things that are genuinely going well.",
  "What's the one thing, if you made progress on it today, that would feel meaningful?",
  "Recall a moment when something just clicked — what was different about that time?",
  "What are you tolerating that you don't have to tolerate?",
  "Write the headline of how you'd like to feel at the end of today.",
  "What's something you've learned recently that surprised you?",
  "What would you tell your earlier self about this kind of situation?",
  "What's the most alive you've felt recently — and what was happening?",
  "Think of a person who energizes you — what is it they actually do?",

  // — sensory resets —
  "Put on one piece of music you love and listen to it fully, without multitasking.",
  "Find something near you with an interesting texture and spend a moment with it.",
  "Light a candle, open a window, or do something small to change the air in your space.",
  "Close your eyes and listen to the soundscape around you for 30 seconds.",
  "Notice five things you can see right now that you're grateful for.",
  "Take a single deep breath, hold it for four counts, exhale for six.",
  "Find the most beautiful thing visible from where you're sitting.",
  "Brew something warm and savour the process of making it.",
  "Place your hands flat on a surface — wood, paper, fabric — and notice the feeling.",
  "Look up. What's on the ceiling, or the sky above you?",
  "Notice the quality of light right now — is it warm, cool, direct, soft?",
  "Find a scent you enjoy — a book, a plant, coffee — and breathe it in.",
  "Sit still for 60 seconds and just notice what your body is doing.",
  "Soften your gaze and let your peripheral vision open up.",
  "Notice the weight of your own body — where you're being supported right now.",

  // — playful experiments —
  "Give yourself exactly 10 minutes to make the fastest, roughest version of something.",
  "Set a timer for 5 minutes and generate 20 wild ideas — quantity over quality.",
  "What's the most ridiculous possible solution to your problem? Now find the seed of something real in it.",
  "Try explaining your idea using only three-syllable-or-less words.",
  "Write your problem as a question, then write five different versions of that question.",
  "Pretend you're pitching your idea to someone who is famously hard to impress.",
  "Make a constraint: now solve it with only what's within arm's reach.",
  "What's the 'wrong' way to do this that might actually work?",
  "Give your project a character — if it were a person, who would it be?",
  "Rename what you're working on. Something that makes it feel fresh.",
  "What's the most joyful version of this? Describe it.",
  "Try the opposite of your instinct, just to see where it leads.",
  "Imagine a version of this that would make people laugh with delight.",
  "What would it look like if you made this ten times bigger? Ten times smaller?",
  "Remove one element that feels essential — and see if anything opens up.",

  // — connection & curiosity —
  "Think of someone you respect — what question would you love to ask them right now?",
  "What's a subject you've been meaning to learn more about for years?",
  "Find one article, book, or piece of work that excites you and save it for later.",
  "Recall a conversation that changed the way you think.",
  "Who in your life has a perspective very different from yours — and what might they see here?",
  "Think of someone doing interesting work — what can you learn from how they approach things?",
  "What's a place you've always wanted to visit, and what draws you to it?",
  "What's something you admired in someone else that you also have in yourself?",
  "Think of a mentor, real or imagined — what would they encourage you to try?",
  "Name three people whose work you'd like to study more deeply.",

  // — rhythm & energy —
  "Do 10 jumping jacks right now. Notice the shift.",
  "Roll your shoulders back, lift your chest, and take up a little more space.",
  "Take three sips of water and notice whether you actually needed them.",
  "Stand up and stretch your arms overhead as high as they'll go.",
  "Take one minute to do nothing at all — not even thinking productively.",
  "Notice where you're holding tension and try to release it.",
  "Do something with your hands that isn't looking at a screen — even for two minutes.",
  "Step outside for air, even just to stand at an open door for a moment.",
  "Put your feet flat on the floor and sit up straight — notice how your energy shifts.",
  "Name one thing you can do right now that's good for your body.",

  // — permission & ease —
  "It's okay to not know yet. What would you do if you had permission to be uncertain?",
  "The first attempt doesn't have to be good — it just has to exist.",
  "Give yourself permission to make something imperfect today.",
  "What would you do right now if you trusted yourself completely?",
  "Remind yourself: being stuck is part of the process, not a failure.",
  "What would feel like play rather than work right now?",
  "You don't need all the answers before you begin. What's the next smallest step?",
  "Let go of the version in your head — what's possible with what you actually have?",
  "Acknowledge one thing you've already done well today.",
  "What would you create if you knew no one would ever judge it?",
  "Give yourself the same encouragement you'd give a good friend.",
  "You're allowed to change direction — what feels more alive right now?",
  "What if you already had enough to start?",
  "Whatever you're making, it matters that you're making it.",
  "You don't need to solve everything at once. What's one thread you can pull?",

  // — wonder & appreciation —
  "Look for something near you that is genuinely beautiful.",
  "Notice something you take for granted that is actually remarkable.",
  "Find one small thing today that surprised you.",
  "Think about something you understood recently that once confused you.",
  "What's something that exists in the world that you're glad someone made?",
  "Name something ordinary that becomes extraordinary when you pay close attention.",
  "What's one thing about being alive that still feels like a miracle to you?",
  "Think of a skill you have that once took real effort to develop.",
  "Notice one way your surroundings are supporting you right now.",
  "What's one thing you love about the way your mind works?",
  "Find something that makes you smile without really knowing why.",
  "Think about a piece of art, music, or writing that changed something in you.",
  "What's one thing you're quietly looking forward to?",
  "Notice the ordinary kindness in something around you.",
  "Think of a moment of unexpected beauty you witnessed recently.",

  // — making & doing —
  "Write one paragraph about what you're working on — for no one but yourself.",
  "Start with the end: describe the finished thing vividly before you begin.",
  "Break the next step into something so small it takes less than five minutes.",
  "Do the hardest three minutes of the work right now — just three minutes.",
  "Set a timer for 25 minutes and commit fully to just this one thing.",
  "Make a rough prototype — physical, digital, or written — before perfecting anything.",
  "Say out loud what you're about to make, as if explaining to a friend.",
  "Write the version that's good enough before reaching for perfect.",
  "Ask: what's the one thing that would make everything else easier?",
  "Just begin — anywhere. The momentum will find you.",
  "Commit to a direction, even if it's imperfect. You can adjust as you go.",
  "Do the thing you've been circling around and avoiding.",
  "Clear a small physical space before you work — notice how it shifts your mind.",
  "Give the next 20 minutes completely to this. Nothing else.",
  "Make something today, even something very small.",

  // — craft & attention —
  "Slow down and notice the detail in whatever you're making right now.",
  "Ask: what would make this 10% more honest?",
  "What's the single most important thing in what you're working on?",
  "What would this look like if it were meant to last?",
  "Where is there unnecessary complexity you could remove?",
  "What would you keep if you had to cut half of this?",
  "What's the part you keep avoiding — and is there something worth finding there?",
  "Imagine someone experiencing your work for the first time — what do they feel?",
  "What's the soul of this thing — the part that would be missing if it were gone?",
  "Read back what you've made so far, as if you're encountering it for the first time.",

  // — rest & renewal —
  "Take a real break — not a scroll. Look at something far away.",
  "The best ideas often come during rest. Give yourself permission to pause.",
  "What would genuine restoration look like right now — even for five minutes?",
  "Step away from the work completely for a short while. It will still be there.",
  "Tiredness is information. What is your body asking for?",
  "Do one nurturing thing for yourself before you continue.",
  "Notice if you've been pushing for a long time — and give yourself credit for that.",
  "Rest isn't wasted time. It's when the mind integrates what it's learned.",
  "What's something small that would make you feel cared for right now?",
  "Close your eyes for 60 seconds. Just breathe.",
];
